name: "Bug report"
description: Create a bug report or help us improve things
body:
  - type: markdown
    attributes:
      value: |
        ##Important information
        Please understand you are asking for support for the Docker- 
        Image and Docker-Container. I'm NOT the creator of the Dedicated-Game-Server itself, i'm not involved in programming that.
        If you need help for that, you might want to ask here for topics related to that: https://steamcommunity.com/app/1326470/discussions/0/3808404524164518482/
   - type: textarea
     id: describe
     attributes:
      label: Describe
      description: Describe
      placeholder: give me ...
     validations:
      reuqire: true
